/**
 * JanusFT.ecies-decode.test.js — ECIES round-trip decode verification for JanusFT v0.8.
 *
 * Proves that the note bytes deposited into ShieldedInbox (via shieldedTransfer or
 * direct_deposit_to_inbox test helper) decrypt correctly to the original note payload.
 *
 * This is the JS side of the "Approach A" hybrid test strategy:
 *   1. Cadence tests verify the bytes are STORED and RETRIEVED faithfully
 *      (tests/cadence/JanusFT.shielded-recovery_test.cdc).
 *   2. This test proves the stored bytes DECRYPT to the correct note content.
 *
 * Uses the pre-computed fixture file generated by:
 *   node tests/helpers/precompute-ciphertexts.mjs
 *
 * Run with Node (no jest required):
 *   node tests/JanusFT.ecies-decode.test.js
 *
 * Or via npm test (if jest is configured):
 *   npm test -- JanusFT.ecies-decode
 */

import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { decryptNoteFromInbox } from "./helpers/verify-decode.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_FILE = join(__dirname, "helpers/ecies-fixtures.json");

// ── Test runner (lightweight, no jest dependency) ─────────────────────────────

let passed = 0;
let failed = 0;

async function test(name, fn) {
    try {
        await fn();
        console.log(`  PASS  ${name}`);
        passed++;
    } catch (e) {
        console.error(`  FAIL  ${name}`);
        console.error(`        ${e.message}`);
        failed++;
    }
}

function assert(condition, msg) {
    if (!condition) throw new Error(msg || "assertion failed");
}

function assertEqual(expected, actual, label) {
    if (expected !== actual) {
        throw new Error(`${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
    }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
    console.log("JanusFT v0.8 — ECIES decode verification\n");

    if (!existsSync(FIXTURES_FILE)) {
        console.error(`ERROR: fixtures file not found at ${FIXTURES_FILE}`);
        console.error("Run: node tests/helpers/precompute-ciphertexts.mjs");
        process.exit(1);
    }

    const fixtures = JSON.parse(readFileSync(FIXTURES_FILE, "utf8"));
    const recipPriv = BigInt(fixtures.recipient.privkey);

    // ── Test 1: Fixture file has expected structure ───────────────────────────

    await test("fixtures file has version 0.8.0", () => {
        assertEqual("0.8.0", fixtures.version, "version");
    });

    await test("fixtures file has at least 2 fixtures", () => {
        assert(fixtures.fixtures.length >= 2, `expected >= 2 fixtures, got ${fixtures.fixtures.length}`);
    });

    await test("recipient privkey is valid non-zero bigint", () => {
        assert(recipPriv > 0n, "privkey must be > 0");
    });

    // ── Test 2: Fixture 1 — 0.30 MockFT note ─────────────────────────────────

    const fix1 = fixtures.fixtures.find(f => f.id === "fixture1");
    assert(fix1, "fixture1 not found in fixtures file");

    await test("fixture1: decrypts successfully", async () => {
        const ct   = new Uint8Array(fix1.ciphertext);
        const ephX = BigInt(fix1.ephPubkeyX);
        const ephY = BigInt(fix1.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assert(decoded !== null, "decoded payload is null");
        assert(typeof decoded === "object", "decoded is not an object");
    });

    await test("fixture1: decoded.amt matches original", async () => {
        const ct     = new Uint8Array(fix1.ciphertext);
        const ephX   = BigInt(fix1.ephPubkeyX);
        const ephY   = BigInt(fix1.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assertEqual(fix1.payload.amt, decoded.amt, "amt");
    });

    await test("fixture1: decoded.bld matches original", async () => {
        const ct     = new Uint8Array(fix1.ciphertext);
        const ephX   = BigInt(fix1.ephPubkeyX);
        const ephY   = BigInt(fix1.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assertEqual(fix1.payload.bld, decoded.bld, "bld");
    });

    await test("fixture1: decoded.memo matches original", async () => {
        const ct     = new Uint8Array(fix1.ciphertext);
        const ephX   = BigInt(fix1.ephPubkeyX);
        const ephY   = BigInt(fix1.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assertEqual(fix1.payload.memo, decoded.memo, "memo");
    });

    await test("fixture1: note version is 1", async () => {
        const ct     = new Uint8Array(fix1.ciphertext);
        const ephX   = BigInt(fix1.ephPubkeyX);
        const ephY   = BigInt(fix1.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assertEqual(1, decoded.v, "note version");
    });

    // ── Test 3: Fixture 2 — 0.10 MockFT note ─────────────────────────────────

    const fix2 = fixtures.fixtures.find(f => f.id === "fixture2");
    assert(fix2, "fixture2 not found in fixtures file");

    await test("fixture2: decrypts and amt matches", async () => {
        const ct     = new Uint8Array(fix2.ciphertext);
        const ephX   = BigInt(fix2.ephPubkeyX);
        const ephY   = BigInt(fix2.ephPubkeyY);
        const decoded = await decryptNoteFromInbox(ct, ephX, ephY, recipPriv);
        assertEqual(fix2.payload.amt, decoded.amt, "fixture2 amt");
        assertEqual(fix2.payload.bld, decoded.bld, "fixture2 bld");
    });

    // ── Test 4: Wrong private key fails authentication ────────────────────────

    await test("wrong privkey: AES-GCM authentication fails", async () => {
        const ct     = new Uint8Array(fix1.ciphertext);
        const ephX   = BigInt(fix1.ephPubkeyX);
        const ephY   = BigInt(fix1.ephPubkeyY);
        const wrongPriv = recipPriv + 1n;
        let threw = false;
        try {
            await decryptNoteFromInbox(ct, ephX, ephY, wrongPriv);
        } catch (e) {
            threw = true;
            assert(
                e.message.includes("authentication failed") || e.message.includes("AES-GCM"),
                `unexpected error: ${e.message}`
            );
        }
        assert(threw, "expected decryption to throw with wrong privkey");
    });

    // ── Test 5: Truncated ciphertext fails ────────────────────────────────────

    await test("truncated ciphertext: throws too-short error", async () => {
        const shortCt = new Uint8Array(10);  // 10 bytes < 12 IV + 16 tag minimum
        const ephX    = BigInt(fix1.ephPubkeyX);
        const ephY    = BigInt(fix1.ephPubkeyY);
        let threw = false;
        try {
            await decryptNoteFromInbox(shortCt, ephX, ephY, recipPriv);
        } catch (e) {
            threw = true;
            assert(
                e.message.includes("too short") || e.message.includes("authentication failed"),
                `unexpected error: ${e.message}`
            );
        }
        assert(threw, "expected decryption to throw for truncated ciphertext");
    });

    // ── Test 6: Cadence bytes match fixture (round-trip integrity) ────────────

    await test("fixture1: ciphertext bytes are non-empty and > 28 bytes", () => {
        // Minimum: 12 (IV) + 1 (plaintext) + 16 (tag) = 29 bytes
        assert(fix1.ciphertext.length > 28, `expected > 28 bytes, got ${fix1.ciphertext.length}`);
    });

    await test("fixture1 and fixture2: distinct ciphertexts (different randomness)", () => {
        const ct1 = JSON.stringify(fix1.ciphertext);
        const ct2 = JSON.stringify(fix2.ciphertext);
        assert(ct1 !== ct2, "fixture1 and fixture2 should produce different ciphertexts");
    });

    // ── Summary ───────────────────────────────────────────────────────────────

    console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed\n`);

    if (failed > 0) {
        console.error(`FAIL — ${failed} test(s) failed`);
        process.exit(1);
    }
    console.log("PASS — all ECIES decode tests passed");
}

main().catch(err => {
    console.error("FATAL:", err.message);
    process.exit(1);
});
