/// JanusFT.shielded-recovery_test.cdc — Cadence unit tests for JanusFT v0.8
/// shielded-recovery integration.
///
/// Run from packages/janus-ft:
///   flow test tests/cadence/JanusFT.shielded-recovery_test.cdc
///
/// Test environment requirements
/// ───────────────────────────────
/// Runs on the Flow emulator ("testing" network, 127.0.0.1:3569).
/// The emulator provides EVM at 0xf8d6e0586b0a20c7 which satisfies the EVM import.
/// JanusFlow (normally at 0x5dcbeb41055ec57e on testnet) is replaced by the
/// minimal JanusFlow_stub deployed in setup().
///
/// Cross-VM-dependent tests (full shieldedTransfer with real ZK proofs) are
/// integration tests covered by smoke-janusft-aggregate.mjs and the ECIES decode
/// verifier (tests/JanusFT.ecies-decode.test.js).
///
/// Coverage
/// ────────
///  1.  Contract deployment + MAX_BATCH_RESET == 100
///  2.  CommitmentRegistry setup (totalLocked == 0)
///  3.  Inbox installation idempotent
///  4.  Checkpoint installation idempotent
///  5.  AdminProofStoragePath equals AdminStoragePath
///  6.  adminResetSlot single slot: commitment → identity
///  7.  adminResetSlot panics for non-existent slot
///  8.  adminBatchResetSlots: 3 set + 1 nil → nil silently skipped, 3 reset
///  9.  adminBatchResetSlots reverts when users.length > 100
/// 10.  SlotReset event emitted on adminResetSlot
/// 11.  Direct inbox deposit: bytes preserved exactly (FIXTURE_CT round-trip)
/// 12.  FIFO order preserved across multiple direct deposits
/// 13.  Multi-recipient isolation (alice→bob and alice→carol independent)
/// 14.  Strict-mode: shieldedTransfer panics when recipient has no inbox
/// 15.  v0.8 event types accessible (ShieldedTransferNote + deprecated wrapper)

import Test
import BlockchainHelpers
import "JanusFT"
import "ShieldedInbox"
import "ShieldedCheckpoint"

// ---------------------------------------------------------------------------
// Test accounts
// ---------------------------------------------------------------------------

access(all) let deployer = Test.getAccount(0x0000000000000013)
access(all) let alice    = Test.createAccount()
access(all) let bob      = Test.createAccount()
access(all) let carol    = Test.createAccount()
/// dave never installs an inbox — used for strict-mode panic test
access(all) let dave     = Test.createAccount()

// ---------------------------------------------------------------------------
// Pre-computed ECIES ciphertext fixtures
// Generated by: node tests/helpers/precompute-ciphertexts.mjs
//
// Recipient: bob's deterministic BabyJub keypair (privkey = 123456789...0123n)
// Payload: {v:1, amt:"30000000", bld:"98765432109876543210987654", memo:"JanusFT-v0.8-test"}
// Decryption verified by: node tests/JanusFT.ecies-decode.test.js
// ---------------------------------------------------------------------------

access(all) let FIXTURE_EPH_X: UInt256 =
    8190521450935416532888494261730315431696489551095848138811014530828875440097
access(all) let FIXTURE_EPH_Y: UInt256 =
    7601091023953723884940914746846574365973801397252898472550077653060548372603
access(all) let FIXTURE_CT: [UInt8] = [
    0xdc, 0x2b, 0x0f, 0xa7, 0x63, 0x42, 0xc9, 0x74,
    0x23, 0x4c, 0x80, 0xf4, 0xe5, 0xeb, 0x8c, 0xb5,
    0xdf, 0xb5, 0xcf, 0x63, 0x1b, 0x45, 0xf5, 0xe7,
    0xfc, 0xc8, 0xe1, 0x0b, 0x1d, 0xff, 0x34, 0x0f,
    0x69, 0x47, 0x3f, 0xaa, 0x28, 0x94, 0x7b, 0xe9,
    0x01, 0xab, 0xe9, 0x62, 0x2c, 0x1e, 0xfc, 0x4e,
    0x04, 0x79, 0xea, 0x2f, 0x49, 0xc0, 0xd3, 0x4f,
    0x9b, 0x08, 0x8f, 0x65, 0x71, 0x94, 0x9f, 0x60,
    0x1a, 0xc8, 0x86, 0x08, 0x7a, 0x47, 0x58, 0x13,
    0xea, 0x8c, 0xcf, 0x02, 0xc7, 0x16, 0x43, 0xdc,
    0xc4, 0x54, 0xc4, 0x28, 0xc4, 0xe1, 0xf4, 0x31,
    0x7b, 0x44, 0x70, 0x05, 0xe6, 0x9f, 0x4f, 0xfa,
    0x0a, 0x67, 0x48, 0x25, 0x6e, 0xd9, 0x34, 0x57,
    0x2b, 0x6d, 0x8a, 0x93, 0x5a, 0x2e, 0x70, 0x50,
    0xb4, 0x16
]

// ---------------------------------------------------------------------------
// Setup height for Test.reset()
// ---------------------------------------------------------------------------

access(all) var setupHeight: UInt64 = 0

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Deploy a contract from source path.
access(all) fun deployFrom(name: String, path: String, args: [AnyStruct]) {
    let err = Test.deployContract(name: name, path: path, arguments: args)
    Test.expect(err, Test.beNil())
}

/// Install ShieldedInbox for a test account (idempotent).
access(all) fun installInbox(signer: Test.TestAccount) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/install_inbox_ft.cdc"),
        authorizers: [signer.address],
        signers:     [signer],
        arguments:   []
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Install ShieldedCheckpoint for a test account (idempotent).
access(all) fun installCheckpoint(signer: Test.TestAccount) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/install_checkpoint_ft.cdc"),
        authorizers: [signer.address],
        signers:     [signer],
        arguments:   []
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Create a CadenceOwnedAccount (COA) for a test account.
access(all) fun createCoa(signer: Test.TestAccount) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/create_coa.cdc"),
        authorizers: [signer.address],
        signers:     [signer],
        arguments:   []
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Deposit a note directly to an inbox (bypasses JanusFT, no ZK needed).
access(all) fun directDeposit(
    depositor:  Test.TestAccount,
    recipient:  Address,
    ciphertext: [UInt8],
    ephX:       UInt256,
    ephY:       UInt256
) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/direct_deposit_to_inbox.cdc"),
        authorizers: [depositor.address],
        signers:     [depositor],
        arguments:   [recipient, ciphertext, ephX, ephY]
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Drain all notes from owner's inbox.
access(all) fun drainAll(owner: Test.TestAccount) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/drain_all_inbox.cdc"),
        authorizers: [owner.address],
        signers:     [owner],
        arguments:   []
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Read pending note count for a user.
access(all) fun getInboxCount(user: Address): Int {
    let r = Test.executeScript(Test.readFile("helpers/get_inbox_count.cdc"), [user])
    Test.expect(r, Test.beSucceeded())
    return r.returnValue! as! Int
}

/// Peek at inbox notes (non-consuming).
access(all) fun peekInbox(user: Address, offset: Int, limit: Int): [ShieldedInbox.Note] {
    let r = Test.executeScript(Test.readFile("helpers/peek_inbox.cdc"), [user, offset, limit])
    Test.expect(r, Test.beSucceeded())
    return r.returnValue! as! [ShieldedInbox.Note]
}

/// Set a commitment for an account (Admin test helper, no ZK needed).
access(all) fun setCommitment(admin: Test.TestAccount, account: Address, x: UInt256, y: UInt256) {
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/set_commitment.cdc"),
        authorizers: [admin.address],
        signers:     [admin],
        arguments:   [account, x, y]
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Read commitment (x, y) for an account.
access(all) fun getCommitment(account: Address): {String: UInt256} {
    let r = Test.executeScript(Test.readFile("helpers/get_commitment.cdc"), [account])
    Test.expect(r, Test.beSucceeded())
    return r.returnValue! as! {String: UInt256}
}

/// Execute adminResetSlot for a user.
access(all) fun doAdminResetSlot(admin: Test.TestAccount, user: Address) {
    let tx = Test.Transaction(
        code:        Test.readFile("../../transactions/admin_reset_slot_ft.cdc"),
        authorizers: [admin.address],
        signers:     [admin],
        arguments:   [user]
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

/// Execute adminBatchResetSlots for a list of users.
access(all) fun doAdminBatchResetSlots(admin: Test.TestAccount, users: [Address]) {
    let tx = Test.Transaction(
        code:        Test.readFile("../../transactions/admin_batch_reset_slots_ft.cdc"),
        authorizers: [admin.address],
        signers:     [admin],
        arguments:   [users]
    )
    Test.expect(Test.executeTransaction(tx), Test.beSucceeded())
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

access(all) fun setup() {
    // Deploy dependencies in order (testing aliases in flow.json must match)
    // 1. JanusFlow stub (JanusFT imports JanusFlow for MemoKey)
    deployFrom(
        name: "JanusFlow",
        path: "helpers/JanusFlow_stub.cdc",
        args: []
    )
    // 2. MockFT (underlying vault for JanusFT)
    deployFrom(
        name: "MockFT",
        path: "../../contracts/cadence/mocks/MockFT.cdc",
        args: []
    )
    // 3. ShieldedInbox (v0.8 STRICT mode dependency)
    deployFrom(
        name: "ShieldedInbox",
        path: "../../../shielded-recovery/contracts/cadence/ShieldedInbox.cdc",
        args: []
    )
    // 4. ShieldedCheckpoint
    deployFrom(
        name: "ShieldedCheckpoint",
        path: "../../../shielded-recovery/contracts/cadence/ShieldedCheckpoint.cdc",
        args: []
    )
    // 5. JanusFT (imports JanusFlow + ShieldedInbox + FungibleToken + EVM)
    deployFrom(
        name: "JanusFT",
        path: "../../contracts/cadence/JanusFT.cdc",
        args: []
    )

    // Configure CommitmentRegistry on the deployer account
    let setupTx = Test.Transaction(
        code:        Test.readFile("helpers/setup_registry.cdc"),
        authorizers: [deployer.address],
        signers:     [deployer],
        arguments:   ["A.0000000000000010.MockFT.Vault"]
    )
    Test.expect(Test.executeTransaction(setupTx), Test.beSucceeded())

    // Install inbox + checkpoint for alice, bob, carol
    installInbox(signer: alice)
    installInbox(signer: bob)
    installInbox(signer: carol)
    installCheckpoint(signer: alice)
    installCheckpoint(signer: bob)
    installCheckpoint(signer: carol)

    // Create COA on alice (needed for strict-mode shieldedTransfer test)
    createCoa(signer: alice)

    setupHeight = getCurrentBlockHeight()
}

/// Reset to post-setup state between tests.
access(all) fun beforeEach() {
    Test.reset(to: setupHeight)
}

// ---------------------------------------------------------------------------
// Test 1 — Contract deployment + MAX_BATCH_RESET constant
// ---------------------------------------------------------------------------

access(all) fun testContractDeployment() {
    let r = Test.executeScript(Test.readFile("helpers/get_max_batch_reset.cdc"), [])
    Test.expect(r, Test.beSucceeded())
    Test.assertEqual(100, r.returnValue! as! Int)
}

// ---------------------------------------------------------------------------
// Test 2 — CommitmentRegistry setup: totalLocked == 0
// ---------------------------------------------------------------------------

access(all) fun testRegistrySetup() {
    let r = Test.executeScript(Test.readFile("helpers/get_total_locked.cdc"), [])
    Test.expect(r, Test.beSucceeded())
    Test.assertEqual(0.0, r.returnValue! as! UFix64)
}

// ---------------------------------------------------------------------------
// Test 3 — Inbox installation is idempotent
// ---------------------------------------------------------------------------

access(all) fun testInboxInstallIdempotent() {
    installInbox(signer: alice)  // second call (first was in setup)
    installInbox(signer: alice)  // third call
    Test.assertEqual(0, getInboxCount(user: alice.address))
}

// ---------------------------------------------------------------------------
// Test 4 — Checkpoint installation is idempotent
// ---------------------------------------------------------------------------

access(all) fun testCheckpointInstallIdempotent() {
    installCheckpoint(signer: alice)  // second call (first was in setup)
    installCheckpoint(signer: alice)  // third call
    // No panic = idempotent confirmed
}

// ---------------------------------------------------------------------------
// Test 5 — AdminProofStoragePath equals AdminStoragePath
// ---------------------------------------------------------------------------

access(all) fun testAdminProofStoragePath() {
    let r = Test.executeScript(Test.readFile("helpers/check_admin_proof_path.cdc"), [])
    Test.expect(r, Test.beSucceeded())
    Test.assertEqual(true, r.returnValue! as! Bool)
}

// ---------------------------------------------------------------------------
// Test 6 — adminResetSlot: single slot cleared to identity
// ---------------------------------------------------------------------------

access(all) fun testAdminResetSlotSingle() {
    let nonZeroX: UInt256 = 12345678901234567890
    let nonZeroY: UInt256 = 98765432109876543210

    setCommitment(admin: deployer, account: alice.address, x: nonZeroX, y: nonZeroY)

    let before = getCommitment(account: alice.address)
    Test.assertEqual(nonZeroX, before["x"]!)
    Test.assertEqual(nonZeroY, before["y"]!)

    doAdminResetSlot(admin: deployer, user: alice.address)

    let after = getCommitment(account: alice.address)
    Test.assertEqual(0 as UInt256, after["x"]!)
    Test.assertEqual(1 as UInt256, after["y"]!)
}

// ---------------------------------------------------------------------------
// Test 7 — adminResetSlot panics for non-existent slot
// ---------------------------------------------------------------------------

access(all) fun testAdminResetSlotNotFound() {
    // dave has never interacted with JanusFT — no slot exists
    let tx = Test.Transaction(
        code:        Test.readFile("../../transactions/admin_reset_slot_ft.cdc"),
        authorizers: [deployer.address],
        signers:     [deployer],
        arguments:   [dave.address]
    )
    Test.expect(Test.executeTransaction(tx), Test.beFailed())
}

// ---------------------------------------------------------------------------
// Test 8 — adminBatchResetSlots: 3 set + 1 nil → nil silently skipped
// ---------------------------------------------------------------------------

access(all) fun testAdminBatchResetSlots() {
    let x: UInt256 = 11111111111111111111
    let y: UInt256 = 22222222222222222222

    setCommitment(admin: deployer, account: alice.address, x: x, y: y)
    setCommitment(admin: deployer, account: bob.address,   x: x, y: y)
    setCommitment(admin: deployer, account: carol.address, x: x, y: y)
    // dave is nil — silently skipped

    doAdminBatchResetSlots(
        admin: deployer,
        users: [alice.address, bob.address, carol.address, dave.address]
    )

    let aliceC = getCommitment(account: alice.address)
    let bobC   = getCommitment(account: bob.address)
    let carolC = getCommitment(account: carol.address)

    Test.assertEqual(0 as UInt256, aliceC["x"]!)
    Test.assertEqual(1 as UInt256, aliceC["y"]!)
    Test.assertEqual(0 as UInt256, bobC["x"]!)
    Test.assertEqual(1 as UInt256, bobC["y"]!)
    Test.assertEqual(0 as UInt256, carolC["x"]!)
    Test.assertEqual(1 as UInt256, carolC["y"]!)
}

// ---------------------------------------------------------------------------
// Test 9 — adminBatchResetSlots reverts when users.length > 100
// ---------------------------------------------------------------------------

access(all) fun testAdminBatchResetSlotsTooLarge() {
    var bigList: [Address] = []
    var i = 0
    while i < 101 {
        bigList.append(dave.address)
        i = i + 1
    }
    let tx = Test.Transaction(
        code:        Test.readFile("../../transactions/admin_batch_reset_slots_ft.cdc"),
        authorizers: [deployer.address],
        signers:     [deployer],
        arguments:   [bigList]
    )
    Test.expect(Test.executeTransaction(tx), Test.beFailed())
}

// ---------------------------------------------------------------------------
// Test 10 — SlotReset event emitted on adminResetSlot
// ---------------------------------------------------------------------------

access(all) fun testSlotResetEventEmitted() {
    setCommitment(admin: deployer, account: alice.address, x: 55555 as UInt256, y: 66666 as UInt256)
    doAdminResetSlot(admin: deployer, user: alice.address)

    let events = Test.eventsOfType(Type<JanusFT.SlotReset>())
    Test.assert(events.length >= 1, message: "Expected at least one SlotReset event")
    let ev = events[events.length - 1] as! JanusFT.SlotReset
    Test.assertEqual(alice.address, ev.user)
}

// ---------------------------------------------------------------------------
// Test 11 — Direct inbox deposit: fixture bytes preserved exactly (ECIES plumbing)
// ---------------------------------------------------------------------------

access(all) fun testDirectDepositBytesPreserved() {
    Test.assertEqual(0, getInboxCount(user: bob.address))

    directDeposit(
        depositor:  alice,
        recipient:  bob.address,
        ciphertext: FIXTURE_CT,
        ephX:       FIXTURE_EPH_X,
        ephY:       FIXTURE_EPH_Y
    )

    Test.assertEqual(1, getInboxCount(user: bob.address))

    let notes = peekInbox(user: bob.address, offset: 0, limit: 1)
    Test.assertEqual(1, notes.length)
    Test.assertEqual(FIXTURE_CT, notes[0].ciphertext)
    Test.assertEqual(FIXTURE_EPH_X, notes[0].ephPubkeyX)
    Test.assertEqual(FIXTURE_EPH_Y, notes[0].ephPubkeyY)
    Test.assertEqual(alice.address, notes[0].depositor)

    drainAll(owner: bob)
    Test.assertEqual(0, getInboxCount(user: bob.address))
}

// ---------------------------------------------------------------------------
// Test 12 — FIFO order preserved across multiple direct deposits
// ---------------------------------------------------------------------------

access(all) fun testMultiDepositFifoOrder() {
    let CT_A: [UInt8] = [0x11]
    let CT_B: [UInt8] = [0x22]
    let CT_C: [UInt8] = [0x33]
    let EPH:  UInt256 = 12345

    directDeposit(depositor: alice, recipient: bob.address, ciphertext: CT_A, ephX: EPH, ephY: EPH)
    directDeposit(depositor: alice, recipient: bob.address, ciphertext: CT_B, ephX: EPH, ephY: EPH)
    directDeposit(depositor: alice, recipient: bob.address, ciphertext: CT_C, ephX: EPH, ephY: EPH)

    Test.assertEqual(3, getInboxCount(user: bob.address))

    let notes = peekInbox(user: bob.address, offset: 0, limit: 3)
    Test.assertEqual(3, notes.length)
    Test.assertEqual(CT_A, notes[0].ciphertext)
    Test.assertEqual(CT_B, notes[1].ciphertext)
    Test.assertEqual(CT_C, notes[2].ciphertext)

    drainAll(owner: bob)
    Test.assertEqual(0, getInboxCount(user: bob.address))
}

// ---------------------------------------------------------------------------
// Test 13 — Multi-recipient isolation
// ---------------------------------------------------------------------------

access(all) fun testMultiRecipientIsolation() {
    let CT_A: [UInt8] = [0xAA]
    let CT_B: [UInt8] = [0xBB]
    let EPH:  UInt256 = 99999

    directDeposit(depositor: alice, recipient: bob.address,   ciphertext: CT_A, ephX: EPH, ephY: EPH)
    directDeposit(depositor: alice, recipient: carol.address,  ciphertext: CT_B, ephX: EPH, ephY: EPH)
    directDeposit(depositor: alice, recipient: bob.address,   ciphertext: CT_A, ephX: EPH, ephY: EPH)

    Test.assertEqual(2, getInboxCount(user: bob.address))
    Test.assertEqual(1, getInboxCount(user: carol.address))
    Test.assertEqual(0, getInboxCount(user: alice.address))

    drainAll(owner: bob)
    Test.assertEqual(0, getInboxCount(user: bob.address))
    Test.assertEqual(1, getInboxCount(user: carol.address))
}

// ---------------------------------------------------------------------------
// Test 14 — Strict-mode: shieldedTransfer panics when recipient has no inbox
// ---------------------------------------------------------------------------

access(all) fun testStrictModeNoInboxPanic() {
    // dave has no inbox — the transaction must fail with:
    // "JanusFT: recipient has not installed ShieldedInbox..."
    // This panic fires BEFORE any cross-VM EVM call (strict-mode check is first).
    let tx = Test.Transaction(
        code:        Test.readFile("helpers/strict_mode_shielded_transfer.cdc"),
        authorizers: [alice.address],
        signers:     [alice],
        arguments:   [alice.address, dave.address]
    )
    Test.expect(Test.executeTransaction(tx), Test.beFailed())
}

// ---------------------------------------------------------------------------
// Test 15 — v0.8 event types accessible (ShieldedTransferNote + deprecated)
// ---------------------------------------------------------------------------

access(all) fun testShieldedTransferNoteEventSchema() {
    let r = Test.executeScript(Test.readFile("helpers/check_event_types.cdc"), [])
    Test.expect(r, Test.beSucceeded())
    Test.assertEqual(true, r.returnValue! as! Bool)
}
