// SPDX-License-Identifier: GPL-3.0
//
// ConfidentialClaimBatchVerifier — Groth16 verifier for the batch shielded-inbox claim circuit.
//
// Circuit:      circuits/aggregate-claim-batch/confidential_claim_batch.circom
// Constraints:  270,325
// Public inputs: [batchRoot, merkleRoot, nullifier_0..N-1, recipient] — 6 signals (IC0..IC6)
// Curve:        BN128 (alt_bn128)
// Protocol:     Groth16
//
// Ceremony:
//   Phase 1:  Hermez powersOfTau28_hez_final_22.ptau (54+ contributors, pot22)
//   Phase 2:  Single contributor (openjanus-batch-claim-contributor-1) + Flow VRF beacon
//   Beacon:   Flow testnet block 325996533
//             (e75b8dc6800a3ebe84958d6fb6632945aecbefe0e38dad05bca96d62dc29ee12)
//   ZKey:     cb_final.zkey  sha256=a5ed2189f2313796d9e38367ca7459966d9db083498b22a0e38ed2b548d2dde1
//   Grade:    pre-mainnet (single phase-2 contributor; multi-party ceremony recommended before mainnet)
//
// Generated by: snarkjs 0.7.6 zkey export solidityverifier
// Contract name: renamed from snarkjs default 'Groth16Verifier' to 'ConfidentialClaimBatchVerifier'.
// All other bytes are canonical snarkjs 0.7.6 output.
// See: circuits/aggregate-claim-batch/ceremony.json for full ceremony record.
//
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

contract ConfidentialClaimBatchVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 constant alphay  = 9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 constant betax1  = 4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 constant betax2  = 6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 constant betay1  = 21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 constant betay2  = 10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 12446662354416038211432199731985436873330044932034719396880459662050248969300;
    uint256 constant deltax2 = 1229400829427982987167326028615682601510569657127071091620269738322595276253;
    uint256 constant deltay1 = 502063869394485593376957391081636451161676520471428030056071375561482641567;
    uint256 constant deltay2 = 6381441938085381305679243803094267971888749955357070896980581655038037857150;


    uint256 constant IC0x = 7876097946123328873371035095123168425363466512707289320935309578880030937952;
    uint256 constant IC0y = 14007117903935895617295533164983294688854635566392554467146842149772052386410;

    uint256 constant IC1x = 15356438266107395953933293144754365827713591234355948099057443439037931237420;
    uint256 constant IC1y = 6117002991219636092543514035112051230205947818609698687744025865068285957922;

    uint256 constant IC2x = 16630595546451784230996015508977818640814050120813892345373756795237470003926;
    uint256 constant IC2y = 1189743646733934810377671534538028568263802203763352560633940777752923952321;

    uint256 constant IC3x = 8494291276355666100932727053035357040779577761028340967477131173566259523482;
    uint256 constant IC3y = 4276912692165375661780338442040995693137901104292685623085504776687473911123;

    uint256 constant IC4x = 18787515465132840635506123413161118832458959333023436196262822629802327539520;
    uint256 constant IC4y = 15952931739607887917429214927045683322469687067486628650702553849311206206989;

    uint256 constant IC5x = 21161075586744503778311230505873934260914353717489156219857673503260076870794;
    uint256 constant IC5y = 238157341426519699897731014046883718221703024448844587000224646732417339487;

    uint256 constant IC6x = 4876330979652713796712960567283666452670680717764552759768749687731360913974;
    uint256 constant IC6y = 5359841396974703564617082131044883302575141841677677524840750048781140309798;


    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[6] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))

                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))

                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))

                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))

                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))

                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))


                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F

            checkField(calldataload(add(_pubSignals, 0)))

            checkField(calldataload(add(_pubSignals, 32)))

            checkField(calldataload(add(_pubSignals, 64)))

            checkField(calldataload(add(_pubSignals, 96)))

            checkField(calldataload(add(_pubSignals, 128)))

            checkField(calldataload(add(_pubSignals, 160)))


            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
